openapi: 3.0.1
info:
  title: Game Deals Genie (PC)
  description: Get current deals on all PC games.
  version: "v1"
servers:
  - url: http://localhost:3000
paths:
  /deals:
    get:
      operationId: getDeals
      summary: Retrieves all games from the API.
      parameters:
        - name: storeID
          in: query
          description: Comma separated list of store ID's to filter on. If not set, all stores will be shown.
          required: false
          schema:
            type: string
        - name: pageNumber
          in: query
          description: The requested page number, value is 0 indexed.
          required: false
          schema:
            type: integer
            default: 0
        - name: pageSize
          in: query
          description: The number of deals per page, max value of 60
          required: false
          schema:
            type: integer
            default: 60
        - name: sortBy
          in: query
          description: Criteria to sort the list by
          required: false
          schema:
            type: string
            default: "Deal Rating"
            enum:
              [
                "Deal Rating",
                "Title",
                "Savings",
                "Price",
                "Metacritic",
                "Reviews",
                "Release",
                "Store",
                "Recent",
              ]
        - name: desc
          in: query
          description: Determines sort direction
          required: false
          schema:
            type: boolean
            default: false
        - name: lowerPrice
          in: query
          description: Only returns deals with a price greater than this value
          required: false
          schema:
            type: integer
            default: 0
        - name: upperPrice
          in: query
          description: Only returns deals with a price less than or equal to this value
          required: false
          schema:
            type: integer
        - name: metacritic
          in: query
          description: Minimum Metacritic rating for a game
          required: false
          schema:
            type: integer
        - name: steamRating
          in: query
          description: Minimum Steam reviews rating for a game
          required: false
          schema:
            type: integer
        - name: steamAppID
          in: query
          description: Look for deals on specific games, comma separated list of Steam App ID
          required: false
          schema:
            type: string
        - name: title
          in: query
          description: Looks for the string contained anywhere in the game name
          required: false
          schema:
            type: string
        - name: exact
          in: query
          description: Flag to allow only exact string match for title parameter, 1 for true and 0 for false
          required: false
          schema:
            type: integer
            default: false
        - name: AAA
          in: query
          description: Flag to include only deals with retail price > $29
          required: false
          schema:
            type: boolean
            default: false
        - name: steamworks
          in: query
          description: Flag to include only deals that redeem on Steam
          required: false
          schema:
            type: boolean
            default: false
        - name: onSale
          in: query
          description: Flag to include only games that are currently on sale
          required: false
          schema:
            type: boolean
            default: false
        - name: output
          in: query
          description: Option to output deals in RSS format
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK

  /getstoreids:
    get:
      operationId: getStoreIds
      summary: Retrieves all store ids from the API.
      responses:
        "200":
          description: OK

  /getcurrencyrates:
    get:
      operationId: getCurrencyRates
      summary: Retrieves all currency rates from the API.
      responses:
        "200":
          description: OK
